### PR TITLE
WASM/WebGL build target support

### PR DESCRIPTION
**Pull request by masonblier**
Hello bwasty et al,

I've done some work to implement a wasm build target for this project, so this gltf viewer can be used in a web browser. 

Screen Shot 2019-11-19 at 7 06 36 AM

The diverged code is in the `platform/gl` or `platform/webgl` directories. Originally I thought to make a new project, but there were fewer changes required than I thought. I am using this repository for a personal web-based gltf file explorer tool, and may also attempt to implement skinning/animations for my own education.

Please let me know any issues or features you think necessary to accompany this PR. 

Thank you for this project and allowing all to learn from and modify the source code.

Building
==
Build the wasm web target with this command. You may need to follow setup instructions from
the [wasm-pack website](https://rustwasm.github.io/docs/wasm-pack/).
```
wasm-pack build --target web -- --no-default-features --features use_wasm_bindgen
```

Known Issues
==
- Mouse rotation/panning jumps sporadically on initial click

### CODE REVIEW

**Comment by bwasty** [comment]
Awesome! I hope I'll find time to have a proper look at the code in the next few days.

**Comment by bwasty** [comment]
Sorry I still haven't looked at it - I hope I'll find the time/motivation over the christmas vacation.

**Comment by masonblier** [comment]
@bwasty No problem, I haven't been able to take a second revision at this yet either, I know there are still some bugs and better testing/interfaces needed.

**Comment by pannous** [comment]
ping

**Pull request closed without merging**
